name = "komuniti-kita"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "komuniti-kita"
database_id = "d22e1132-0862-4502-b5a5-74930062fb05"

[[r2_buckets]]
binding = "R2"
bucket_name = "komuniti-kita"

[vars]
API_BASE = "/api"
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""