/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as HomestayHomestayIdRouteImport } from './routes/homestay/$homestayId'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTenantsIndexRouteImport } from './routes/_authenticated/tenants/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedHomestayIndexRouteImport } from './routes/_authenticated/homestay/index'
import { Route as AuthenticatedHomestayRecordIndexRouteImport } from './routes/_authenticated/homestay-record/index'
import { Route as AuthenticatedDirectoryIndexRouteImport } from './routes/_authenticated/directory/index'
import { Route as AuthenticatedCheckpointsIndexRouteImport } from './routes/_authenticated/checkpoints/index'
import { Route as AuthenticatedCheckInIndexRouteImport } from './routes/_authenticated/check-in/index'
import { Route as AuthenticatedCheckInLogsIndexRouteImport } from './routes/_authenticated/check-in-logs/index'
import { Route as AuthenticatedBillingIndexRouteImport } from './routes/_authenticated/billing/index'
import { Route as AuthenticatedSettingsCheckInRouteImport } from './routes/_authenticated/settings/check-in'
import { Route as AuthenticatedSettingsChangePasswordRouteImport } from './routes/_authenticated/settings/change-password'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings/billing'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedHomestayRecordRouteImport } from './routes/_authenticated/homestay/record'
import { Route as AuthenticatedHomestayListingRouteImport } from './routes/_authenticated/homestay/listing'
import { Route as AuthenticatedHomestayListHomestayIdRouteImport } from './routes/_authenticated/homestay-list/$homestayId'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedCheckInLogsRouteImport } from './routes/_authenticated/check-in/logs'
import { Route as AuthenticatedCheckInConfigurationRouteImport } from './routes/_authenticated/check-in/configuration'
import { Route as AuthenticatedCheckInCheckpointsRouteImport } from './routes/_authenticated/check-in/checkpoints'
import { Route as AuthenticatedBillingSettingsRouteImport } from './routes/_authenticated/billing/settings'
import { Route as AuthenticatedBillingReviewRouteImport } from './routes/_authenticated/billing/review'
import { Route as AuthenticatedAuthUsersRouteImport } from './routes/_authenticated/auth/users'
import { Route as AuthenticatedAuthRolesRouteImport } from './routes/_authenticated/auth/roles'

const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const HomestayHomestayIdRoute = HomestayHomestayIdRouteImport.update({
  id: '/homestay/$homestayId',
  path: '/homestay/$homestayId',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsIndexRoute =
  AuthenticatedTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomestayIndexRoute =
  AuthenticatedHomestayIndexRouteImport.update({
    id: '/homestay/',
    path: '/homestay/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomestayRecordIndexRoute =
  AuthenticatedHomestayRecordIndexRouteImport.update({
    id: '/homestay-record/',
    path: '/homestay-record/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDirectoryIndexRoute =
  AuthenticatedDirectoryIndexRouteImport.update({
    id: '/directory/',
    path: '/directory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckpointsIndexRoute =
  AuthenticatedCheckpointsIndexRouteImport.update({
    id: '/checkpoints/',
    path: '/checkpoints/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckInIndexRoute =
  AuthenticatedCheckInIndexRouteImport.update({
    id: '/check-in/',
    path: '/check-in/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckInLogsIndexRoute =
  AuthenticatedCheckInLogsIndexRouteImport.update({
    id: '/check-in-logs/',
    path: '/check-in-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingIndexRoute =
  AuthenticatedBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCheckInRoute =
  AuthenticatedSettingsCheckInRouteImport.update({
    id: '/check-in',
    path: '/check-in',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsChangePasswordRoute =
  AuthenticatedSettingsChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHomestayRecordRoute =
  AuthenticatedHomestayRecordRouteImport.update({
    id: '/homestay/record',
    path: '/homestay/record',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomestayListingRoute =
  AuthenticatedHomestayListingRouteImport.update({
    id: '/homestay/listing',
    path: '/homestay/listing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomestayListHomestayIdRoute =
  AuthenticatedHomestayListHomestayIdRouteImport.update({
    id: '/homestay-list/$homestayId',
    path: '/homestay-list/$homestayId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckInLogsRoute =
  AuthenticatedCheckInLogsRouteImport.update({
    id: '/check-in/logs',
    path: '/check-in/logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckInConfigurationRoute =
  AuthenticatedCheckInConfigurationRouteImport.update({
    id: '/check-in/configuration',
    path: '/check-in/configuration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckInCheckpointsRoute =
  AuthenticatedCheckInCheckpointsRouteImport.update({
    id: '/check-in/checkpoints',
    path: '/check-in/checkpoints',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingSettingsRoute =
  AuthenticatedBillingSettingsRouteImport.update({
    id: '/billing/settings',
    path: '/billing/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingReviewRoute =
  AuthenticatedBillingReviewRouteImport.update({
    id: '/billing/review',
    path: '/billing/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuthUsersRoute = AuthenticatedAuthUsersRouteImport.update({
  id: '/auth/users',
  path: '/auth/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuthRolesRoute = AuthenticatedAuthRolesRouteImport.update({
  id: '/auth/roles',
  path: '/auth/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/payment': typeof PaymentRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/homestay/$homestayId': typeof HomestayHomestayIdRoute
  '/auth/roles': typeof AuthenticatedAuthRolesRoute
  '/auth/users': typeof AuthenticatedAuthUsersRoute
  '/billing/review': typeof AuthenticatedBillingReviewRoute
  '/billing/settings': typeof AuthenticatedBillingSettingsRoute
  '/check-in/checkpoints': typeof AuthenticatedCheckInCheckpointsRoute
  '/check-in/configuration': typeof AuthenticatedCheckInConfigurationRoute
  '/check-in/logs': typeof AuthenticatedCheckInLogsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/homestay-list/$homestayId': typeof AuthenticatedHomestayListHomestayIdRoute
  '/homestay/listing': typeof AuthenticatedHomestayListingRoute
  '/homestay/record': typeof AuthenticatedHomestayRecordRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/change-password': typeof AuthenticatedSettingsChangePasswordRoute
  '/settings/check-in': typeof AuthenticatedSettingsCheckInRoute
  '/billing/': typeof AuthenticatedBillingIndexRoute
  '/check-in-logs/': typeof AuthenticatedCheckInLogsIndexRoute
  '/check-in/': typeof AuthenticatedCheckInIndexRoute
  '/checkpoints/': typeof AuthenticatedCheckpointsIndexRoute
  '/directory/': typeof AuthenticatedDirectoryIndexRoute
  '/homestay-record/': typeof AuthenticatedHomestayRecordIndexRoute
  '/homestay/': typeof AuthenticatedHomestayIndexRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/payment': typeof PaymentRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/homestay/$homestayId': typeof HomestayHomestayIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth/roles': typeof AuthenticatedAuthRolesRoute
  '/auth/users': typeof AuthenticatedAuthUsersRoute
  '/billing/review': typeof AuthenticatedBillingReviewRoute
  '/billing/settings': typeof AuthenticatedBillingSettingsRoute
  '/check-in/checkpoints': typeof AuthenticatedCheckInCheckpointsRoute
  '/check-in/configuration': typeof AuthenticatedCheckInConfigurationRoute
  '/check-in/logs': typeof AuthenticatedCheckInLogsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/homestay-list/$homestayId': typeof AuthenticatedHomestayListHomestayIdRoute
  '/homestay/listing': typeof AuthenticatedHomestayListingRoute
  '/homestay/record': typeof AuthenticatedHomestayRecordRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/change-password': typeof AuthenticatedSettingsChangePasswordRoute
  '/settings/check-in': typeof AuthenticatedSettingsCheckInRoute
  '/billing': typeof AuthenticatedBillingIndexRoute
  '/check-in-logs': typeof AuthenticatedCheckInLogsIndexRoute
  '/check-in': typeof AuthenticatedCheckInIndexRoute
  '/checkpoints': typeof AuthenticatedCheckpointsIndexRoute
  '/directory': typeof AuthenticatedDirectoryIndexRoute
  '/homestay-record': typeof AuthenticatedHomestayRecordIndexRoute
  '/homestay': typeof AuthenticatedHomestayIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tenants': typeof AuthenticatedTenantsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/payment': typeof PaymentRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/homestay/$homestayId': typeof HomestayHomestayIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/auth/roles': typeof AuthenticatedAuthRolesRoute
  '/_authenticated/auth/users': typeof AuthenticatedAuthUsersRoute
  '/_authenticated/billing/review': typeof AuthenticatedBillingReviewRoute
  '/_authenticated/billing/settings': typeof AuthenticatedBillingSettingsRoute
  '/_authenticated/check-in/checkpoints': typeof AuthenticatedCheckInCheckpointsRoute
  '/_authenticated/check-in/configuration': typeof AuthenticatedCheckInConfigurationRoute
  '/_authenticated/check-in/logs': typeof AuthenticatedCheckInLogsRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/homestay-list/$homestayId': typeof AuthenticatedHomestayListHomestayIdRoute
  '/_authenticated/homestay/listing': typeof AuthenticatedHomestayListingRoute
  '/_authenticated/homestay/record': typeof AuthenticatedHomestayRecordRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/change-password': typeof AuthenticatedSettingsChangePasswordRoute
  '/_authenticated/settings/check-in': typeof AuthenticatedSettingsCheckInRoute
  '/_authenticated/billing/': typeof AuthenticatedBillingIndexRoute
  '/_authenticated/check-in-logs/': typeof AuthenticatedCheckInLogsIndexRoute
  '/_authenticated/check-in/': typeof AuthenticatedCheckInIndexRoute
  '/_authenticated/checkpoints/': typeof AuthenticatedCheckpointsIndexRoute
  '/_authenticated/directory/': typeof AuthenticatedDirectoryIndexRoute
  '/_authenticated/homestay-record/': typeof AuthenticatedHomestayRecordIndexRoute
  '/_authenticated/homestay/': typeof AuthenticatedHomestayIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/payment'
    | '/settings'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/homestay/$homestayId'
    | '/auth/roles'
    | '/auth/users'
    | '/billing/review'
    | '/billing/settings'
    | '/check-in/checkpoints'
    | '/check-in/configuration'
    | '/check-in/logs'
    | '/errors/$error'
    | '/homestay-list/$homestayId'
    | '/homestay/listing'
    | '/homestay/record'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/change-password'
    | '/settings/check-in'
    | '/billing/'
    | '/check-in-logs/'
    | '/check-in/'
    | '/checkpoints/'
    | '/directory/'
    | '/homestay-record/'
    | '/homestay/'
    | '/roles/'
    | '/settings/'
    | '/tenants/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/payment'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/homestay/$homestayId'
    | '/'
    | '/auth/roles'
    | '/auth/users'
    | '/billing/review'
    | '/billing/settings'
    | '/check-in/checkpoints'
    | '/check-in/configuration'
    | '/check-in/logs'
    | '/errors/$error'
    | '/homestay-list/$homestayId'
    | '/homestay/listing'
    | '/homestay/record'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/change-password'
    | '/settings/check-in'
    | '/billing'
    | '/check-in-logs'
    | '/check-in'
    | '/checkpoints'
    | '/directory'
    | '/homestay-record'
    | '/homestay'
    | '/roles'
    | '/settings'
    | '/tenants'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/payment'
    | '/_authenticated/settings'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/homestay/$homestayId'
    | '/_authenticated/'
    | '/_authenticated/auth/roles'
    | '/_authenticated/auth/users'
    | '/_authenticated/billing/review'
    | '/_authenticated/billing/settings'
    | '/_authenticated/check-in/checkpoints'
    | '/_authenticated/check-in/configuration'
    | '/_authenticated/check-in/logs'
    | '/_authenticated/errors/$error'
    | '/_authenticated/homestay-list/$homestayId'
    | '/_authenticated/homestay/listing'
    | '/_authenticated/homestay/record'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/change-password'
    | '/_authenticated/settings/check-in'
    | '/_authenticated/billing/'
    | '/_authenticated/check-in-logs/'
    | '/_authenticated/check-in/'
    | '/_authenticated/checkpoints/'
    | '/_authenticated/directory/'
    | '/_authenticated/homestay-record/'
    | '/_authenticated/homestay/'
    | '/_authenticated/roles/'
    | '/_authenticated/settings/'
    | '/_authenticated/tenants/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PaymentRoute: typeof PaymentRoute
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  HomestayHomestayIdRoute: typeof HomestayHomestayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/homestay/$homestayId': {
      id: '/homestay/$homestayId'
      path: '/homestay/$homestayId'
      fullPath: '/homestay/$homestayId'
      preLoaderRoute: typeof HomestayHomestayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants/': {
      id: '/_authenticated/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AuthenticatedTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/homestay/': {
      id: '/_authenticated/homestay/'
      path: '/homestay'
      fullPath: '/homestay/'
      preLoaderRoute: typeof AuthenticatedHomestayIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/homestay-record/': {
      id: '/_authenticated/homestay-record/'
      path: '/homestay-record'
      fullPath: '/homestay-record/'
      preLoaderRoute: typeof AuthenticatedHomestayRecordIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/directory/': {
      id: '/_authenticated/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof AuthenticatedDirectoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkpoints/': {
      id: '/_authenticated/checkpoints/'
      path: '/checkpoints'
      fullPath: '/checkpoints/'
      preLoaderRoute: typeof AuthenticatedCheckpointsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in/': {
      id: '/_authenticated/check-in/'
      path: '/check-in'
      fullPath: '/check-in/'
      preLoaderRoute: typeof AuthenticatedCheckInIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in-logs/': {
      id: '/_authenticated/check-in-logs/'
      path: '/check-in-logs'
      fullPath: '/check-in-logs/'
      preLoaderRoute: typeof AuthenticatedCheckInLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/': {
      id: '/_authenticated/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthenticatedBillingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/check-in': {
      id: '/_authenticated/settings/check-in'
      path: '/check-in'
      fullPath: '/settings/check-in'
      preLoaderRoute: typeof AuthenticatedSettingsCheckInRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/change-password': {
      id: '/_authenticated/settings/change-password'
      path: '/change-password'
      fullPath: '/settings/change-password'
      preLoaderRoute: typeof AuthenticatedSettingsChangePasswordRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/homestay/record': {
      id: '/_authenticated/homestay/record'
      path: '/homestay/record'
      fullPath: '/homestay/record'
      preLoaderRoute: typeof AuthenticatedHomestayRecordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/homestay/listing': {
      id: '/_authenticated/homestay/listing'
      path: '/homestay/listing'
      fullPath: '/homestay/listing'
      preLoaderRoute: typeof AuthenticatedHomestayListingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/homestay-list/$homestayId': {
      id: '/_authenticated/homestay-list/$homestayId'
      path: '/homestay-list/$homestayId'
      fullPath: '/homestay-list/$homestayId'
      preLoaderRoute: typeof AuthenticatedHomestayListHomestayIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in/logs': {
      id: '/_authenticated/check-in/logs'
      path: '/check-in/logs'
      fullPath: '/check-in/logs'
      preLoaderRoute: typeof AuthenticatedCheckInLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in/configuration': {
      id: '/_authenticated/check-in/configuration'
      path: '/check-in/configuration'
      fullPath: '/check-in/configuration'
      preLoaderRoute: typeof AuthenticatedCheckInConfigurationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in/checkpoints': {
      id: '/_authenticated/check-in/checkpoints'
      path: '/check-in/checkpoints'
      fullPath: '/check-in/checkpoints'
      preLoaderRoute: typeof AuthenticatedCheckInCheckpointsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/settings': {
      id: '/_authenticated/billing/settings'
      path: '/billing/settings'
      fullPath: '/billing/settings'
      preLoaderRoute: typeof AuthenticatedBillingSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/review': {
      id: '/_authenticated/billing/review'
      path: '/billing/review'
      fullPath: '/billing/review'
      preLoaderRoute: typeof AuthenticatedBillingReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auth/users': {
      id: '/_authenticated/auth/users'
      path: '/auth/users'
      fullPath: '/auth/users'
      preLoaderRoute: typeof AuthenticatedAuthUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auth/roles': {
      id: '/_authenticated/auth/roles'
      path: '/auth/roles'
      fullPath: '/auth/roles'
      preLoaderRoute: typeof AuthenticatedAuthRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsChangePasswordRoute: typeof AuthenticatedSettingsChangePasswordRoute
  AuthenticatedSettingsCheckInRoute: typeof AuthenticatedSettingsCheckInRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
    AuthenticatedSettingsChangePasswordRoute:
      AuthenticatedSettingsChangePasswordRoute,
    AuthenticatedSettingsCheckInRoute: AuthenticatedSettingsCheckInRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAuthRolesRoute: typeof AuthenticatedAuthRolesRoute
  AuthenticatedAuthUsersRoute: typeof AuthenticatedAuthUsersRoute
  AuthenticatedBillingReviewRoute: typeof AuthenticatedBillingReviewRoute
  AuthenticatedBillingSettingsRoute: typeof AuthenticatedBillingSettingsRoute
  AuthenticatedCheckInCheckpointsRoute: typeof AuthenticatedCheckInCheckpointsRoute
  AuthenticatedCheckInConfigurationRoute: typeof AuthenticatedCheckInConfigurationRoute
  AuthenticatedCheckInLogsRoute: typeof AuthenticatedCheckInLogsRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedHomestayListHomestayIdRoute: typeof AuthenticatedHomestayListHomestayIdRoute
  AuthenticatedHomestayListingRoute: typeof AuthenticatedHomestayListingRoute
  AuthenticatedHomestayRecordRoute: typeof AuthenticatedHomestayRecordRoute
  AuthenticatedBillingIndexRoute: typeof AuthenticatedBillingIndexRoute
  AuthenticatedCheckInLogsIndexRoute: typeof AuthenticatedCheckInLogsIndexRoute
  AuthenticatedCheckInIndexRoute: typeof AuthenticatedCheckInIndexRoute
  AuthenticatedCheckpointsIndexRoute: typeof AuthenticatedCheckpointsIndexRoute
  AuthenticatedDirectoryIndexRoute: typeof AuthenticatedDirectoryIndexRoute
  AuthenticatedHomestayRecordIndexRoute: typeof AuthenticatedHomestayRecordIndexRoute
  AuthenticatedHomestayIndexRoute: typeof AuthenticatedHomestayIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedTenantsIndexRoute: typeof AuthenticatedTenantsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAuthRolesRoute: AuthenticatedAuthRolesRoute,
  AuthenticatedAuthUsersRoute: AuthenticatedAuthUsersRoute,
  AuthenticatedBillingReviewRoute: AuthenticatedBillingReviewRoute,
  AuthenticatedBillingSettingsRoute: AuthenticatedBillingSettingsRoute,
  AuthenticatedCheckInCheckpointsRoute: AuthenticatedCheckInCheckpointsRoute,
  AuthenticatedCheckInConfigurationRoute:
    AuthenticatedCheckInConfigurationRoute,
  AuthenticatedCheckInLogsRoute: AuthenticatedCheckInLogsRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedHomestayListHomestayIdRoute:
    AuthenticatedHomestayListHomestayIdRoute,
  AuthenticatedHomestayListingRoute: AuthenticatedHomestayListingRoute,
  AuthenticatedHomestayRecordRoute: AuthenticatedHomestayRecordRoute,
  AuthenticatedBillingIndexRoute: AuthenticatedBillingIndexRoute,
  AuthenticatedCheckInLogsIndexRoute: AuthenticatedCheckInLogsIndexRoute,
  AuthenticatedCheckInIndexRoute: AuthenticatedCheckInIndexRoute,
  AuthenticatedCheckpointsIndexRoute: AuthenticatedCheckpointsIndexRoute,
  AuthenticatedDirectoryIndexRoute: AuthenticatedDirectoryIndexRoute,
  AuthenticatedHomestayRecordIndexRoute: AuthenticatedHomestayRecordIndexRoute,
  AuthenticatedHomestayIndexRoute: AuthenticatedHomestayIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedTenantsIndexRoute: AuthenticatedTenantsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PaymentRoute: PaymentRoute,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  HomestayHomestayIdRoute: HomestayHomestayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
